In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics
data = pd.read_csv('iris.csv')

data.head(10)
data.shape

(150, 5)

In [13]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

predicted = logr.predict([[5.0,3.6,1.4,0.2]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-setosa']
     SepalLength  SepalWidth  PetalLength  PetalWidth
72           6.3         2.5          4.9         1.5
118          7.7         2.6          6.9         2.3
0            5.1         3.5          1.4         0.2
75           6.6         3.0          4.4         1.4
105          7.6         3.0          6.6         2.1
142          5.8         2.7          5.1         1.9
40           5.0         3.5          1.3         0.3
102          7.1         3.0          5.9         2.1
79           5.7         2.6          3.5         1.0
21           5.1         3.7          1.5         0.4
64           5.6         2.9          3.6         1.3
124          6.7         3.3          5.7         2.1
23           5.1         3.3          1.7         0.5
45           4.8         3.0          1.4         0.3
96           5.7         2.9          4.2         1.3
119          6.0         2.2          5.0         1.5
130          7.4         2.8          6.1         1.9
16          

/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [14]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0  9  0]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         8
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [15]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

predicted = logr.predict([[5.0,3.6,1.4,0.2]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-setosa']
     SepalLength  SepalWidth  PetalLength  PetalWidth
72           6.3         2.5          4.9         1.5
114          5.8         2.8          5.1         2.4
129          7.2         3.0          5.8         1.6
98           5.1         2.5          3.0         1.1
41           4.5         2.3          1.3         0.3
149          5.9         3.0          5.1         1.8
67           5.8         2.7          4.1         1.0
86           6.7         3.1          4.7         1.5
81           5.5         2.4          3.7         1.0
4            5.0         3.6          1.4         0.2
48           5.3         3.7          1.5         0.2
64           5.6         2.9          3.6         1.3
139          6.9         3.1          5.4         2.1
17           5.1         3.5          1.4         0.3
79           5.7         2.6          3.5         1.0
112          6.8         3.0          5.5         2.1
33           5.5         4.2          1.4         0.2
62          

/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [16]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14  0  0]
 [ 0 18  0]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      1.00      1.00        18
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45



In [17]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

predicted = logr.predict([[5.0,3.6,1.4,0.2]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-setosa']
     SepalLength  SepalWidth  PetalLength  PetalWidth
29           4.7         3.2          1.6         0.2
94           5.6         2.7          4.2         1.3
25           5.0         3.0          1.6         0.2
144          6.7         3.3          5.7         2.5
102          7.1         3.0          5.9         2.1
114          5.8         2.8          5.1         2.4
83           6.0         2.7          5.1         1.6
67           5.8         2.7          4.1         1.0
105          7.6         3.0          6.6         2.1
145          6.7         3.0          5.2         2.3
3            4.6         3.1          1.5         0.2
2            4.7         3.2          1.3         0.2
140          6.7         3.1          5.6         2.4
108          6.7         2.5          5.8         1.8
95           5.7         3.0          4.2         1.2
75           6.6         3.0          4.4         1.4
101          5.8         2.7          5.1         1.9
59          

/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [18]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[12  0  0]
 [ 0 21  1]
 [ 0  0 19]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.95      0.98        22
 Iris-virginica       0.95      1.00      0.97        19

       accuracy                           0.98        53
      macro avg       0.98      0.98      0.98        53
   weighted avg       0.98      0.98      0.98        53



In [23]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

predicted = logr.predict([[5.0,3.6,1.4,0.2]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-setosa']
     SepalLength  SepalWidth  PetalLength  PetalWidth
113          5.7         2.5          5.0         2.0
107          7.3         2.9          6.3         1.8
127          6.1         3.0          4.9         1.8
52           6.9         3.1          4.9         1.5
48           5.3         3.7          1.5         0.2
108          6.7         2.5          5.8         1.8
51           6.4         3.2          4.5         1.5
69           5.6         2.5          3.9         1.1
100          6.3         3.3          6.0         2.5
129          7.2         3.0          5.8         1.6
0            5.1         3.5          1.4         0.2
97           6.2         2.9          4.3         1.3
141          6.9         3.1          5.1         2.3
38           4.4         3.0          1.3         0.2
17           5.1         3.5          1.4         0.3
117          7.7         3.8          6.7         2.2
44           5.1         3.8          1.9         0.4
102         

/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [24]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[20  0  0]
 [ 0 19  1]
 [ 0  1 19]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        20
Iris-versicolor       0.95      0.95      0.95        20
 Iris-virginica       0.95      0.95      0.95        20

       accuracy                           0.97        60
      macro avg       0.97      0.97      0.97        60
   weighted avg       0.97      0.97      0.97        60



In [25]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

predicted = logr.predict([[7.6,3.0,6.6,2.1]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-virginica']
     SepalLength  SepalWidth  PetalLength  PetalWidth
1            4.9         3.0          1.4         0.2
103          6.3         2.9          5.6         1.8
115          6.4         3.2          5.3         2.3
24           4.8         3.4          1.9         0.2
54           6.5         2.8          4.6         1.5
31           5.4         3.4          1.5         0.4
21           5.1         3.7          1.5         0.4
61           5.9         3.0          4.2         1.5
101          5.8         2.7          5.1         1.9
92           5.8         2.6          4.0         1.2
99           5.7         2.8          4.1         1.3
49           5.0         3.3          1.4         0.2
11           4.8         3.4          1.6         0.2
68           6.2         2.2          4.5         1.5
71           6.1         2.8          4.0         1.3
109          7.2         3.6          6.1         2.5
138          6.0         3.0          4.8         1.8
29       

/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [26]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[11  0  0]
 [ 0 11  0]
 [ 0  0  8]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        11
Iris-versicolor       1.00      1.00      1.00        11
 Iris-virginica       1.00      1.00      1.00         8

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [27]:
X = data.drop('Name', axis=1)
y = data['Name']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35)
logr = linear_model.LogisticRegression()
logr.fit(X_train,y_train)

predicted = logr.predict([[1,2,3,4]])

print(predicted)
y_pred = logr.predict(X_test)
print(X_test,y_pred )

['Iris-virginica']
     SepalLength  SepalWidth  PetalLength  PetalWidth
96           5.7         2.9          4.2         1.3
59           5.2         2.7          3.9         1.4
137          6.4         3.1          5.5         1.8
24           4.8         3.4          1.9         0.2
142          5.8         2.7          5.1         1.9
69           5.6         2.5          3.9         1.1
65           6.7         3.1          4.4         1.4
14           5.8         4.0          1.2         0.2
122          7.7         2.8          6.7         2.0
68           6.2         2.2          4.5         1.5
123          6.3         2.7          4.9         1.8
48           5.3         3.7          1.5         0.2
38           4.4         3.0          1.3         0.2
92           5.8         2.6          4.0         1.2
41           4.5         2.3          1.3         0.3
55           5.7         2.8          4.5         1.3
120          6.9         3.2          5.7         2.3
44       

/Users/rajthakur/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [28]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[16  0  0]
 [ 0 20  0]
 [ 0  0 17]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      1.00      1.00        20
 Iris-virginica       1.00      1.00      1.00        17

       accuracy                           1.00        53
      macro avg       1.00      1.00      1.00        53
   weighted avg       1.00      1.00      1.00        53

